version: '3.8'

services:

  redis:
    image: redis:7.2-alpine

  django:
    build:
      context: ./upload_and_process_file_picasso
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./upload_and_process_file_picasso:/usr/src/app/
    ports:
      - '8001:8000'
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build:
      context: ./upload_and_process_file_picasso
    volumes:
      - ./upload_and_process_file_picasso:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis